common: enable C++ TAs by default on x86_64 hosts only
On non-x86_64 hosts, "make toolchains" builds GCC with Buildroot and
that is version 12.x currently. Unfortunatly, C++ support in TAs
requires GCC <= 11 or the following error occurs:

   LD      out/5b9e0e40-2636-11e1-ad9e-0002a5d5c51b.elf
 .../toolchains/aarch64/bin/aarch64-linux-ld.bfd: .../toolchains/aarch64/bin/../lib/gcc/aarch64-buildroot-linux-gnu/12.3.0/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `_Unwind_Find_FDE':
 .../out-aarch64-sdk/build/host-gcc-final-12.3.0/build/aarch64-buildroot-linux-gnu/libgcc/../../../libgcc/unwind-dw2-fde-dip.c:512: undefined reference to `_dl_find_object'
 make[3]: *** [.../optee_os/out/arm/export-ta_arm64/mk/link.mk:123: out/5b9e0e40-2636-11e1-ad9e-0002a5d5c51b.elf] Error 1
 make[2]: *** [package/pkg-generic.mk:284: .../out-br/build/optee_test_ext-1.0/.stamp_built] Error 2
 make[1]: *** [Makefile:23: _all] Error 2

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>